### ISSUE TITLE
formattedName

### ISSUE THREAD

**Issue by DavidOaxaca** [udacity/frontend-nanodegree-resume#129]

**Comment by samuelsilvadev** [comment]
which your question?

**Comment by marcellmar** [comment]
helper.js shows multiple errors in all of my editors (atom, sublime, brackets). is there an updated file?

![helperjserrors](https://cloud.githubusercontent.com/assets/14105778/23338374/4270182a-fc44-11e6-97ba-a905582be55d.jpeg)
