### ISSUE TITLE
Wrong nr of bytes for pageStats check?

### ISSUE THREAD

**Issue by upnorth** [udacity/frontend-nanodegree-resume#259]
Just finished the course, including the optional challenges. However, I hade a very odd error where adding the bytes of the pageStats ended up with 53 bytes too much in the test-run. After having double checked evreything I could think of, I tested with just subtracting that number from the result in the algorithm - which made my code pass all the tests!?

Hoping this is a badly written test, but in case my solution is somehow wrong, this is the code:
```
// Iterate through the localizedRuleNames in ruleResults and 
// return an array of their strings.
function ruleList(results) {
    var list = [];
    for (var key in results.formattedResults.ruleResults) {
        for (var name in results.formattedResults.ruleResults[key]) {
            if (name === "localizedRuleName") {
                list.push(results.formattedResults.ruleResults[key][name]);
            }
        }
    }
    
    // Your code goes here!
    return list;
}

// Iterate through pageStats in the psiResults object and 
// return the total number of bytes to load the website.
function totalBytes(results) {
    var bytes = 0;
    // Your code goes here!
    for (var key in results.pageStats) {
//        if (results.pageStats.hasOwnProperty(key)) {
            bytes += parseInt(results.pageStats[key]);
  //      }
    }
    return bytes -= 53;
}
```

**Comment by mak-chan** [comment]
You haven't read the question well enough. You are adding the value of all the elements of pageStats, but you only have to add the bytes, these are in string type. 53 is the sum of the integars in pageStats which you do not have to add.

![capture](https://cloud.githubusercontent.com/assets/16956850/23831814/78ecba60-074e-11e7-8b68-9352603b2703.PNG)

**Comment by upnorth** [comment]
Haha, how about that...

Den 12 mars 2017 13:35 skrev "Mayank Chauhan" <notifications@github.com>:
