### ISSUE TITLE
Maximum call stack size exceeded error

### ISSUE THREAD

**Issue by aj65461** [udacity/frontend-nanodegree-resume#51]
In helper.js the lat and lng variables in the createMapMarker function read as:

```javascript
var lat = placeData.geometry.location.k;
var lon = placeData.geometry.location.B;
```

The problem is that the k and B are undocumented object properties and can change at anytime. The k and B should be replaced with lat() and lng() like this:

```javascript
var lat = placeData.geometry.location.lat();
var lon = placeData.geometry.location.lng();
```

[Source](http://stackoverflow.com/questions/27420052/google-map-api-v3-maximum-call-stack-size-exceeded)

**Comment by hkasemir** [comment]
fixed in commit Dec 12, 2014 - https://github.com/udacity/frontend-nanodegree-resume/commit/563a0cf7513c96ea3b2cdd0bbd148c07067512d1
